[package]
name = "mysql"
version = "0.1.0"
authors = ["katand <katandps@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#beatoraja_play_recommend = { git = "https://github.com/katandps/beatoraja_play_recommend.git", rev = "d15136f4" }
#開発用
beatoraja_play_recommend = { path = "../../../beatoraja_play_recommend" }

diesel = { version = "1.4.4", features = ["mysql"]}
diesel_codegen = "0.16.1"

#エラー処理
anyhow = "1.0"
