version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
    commands:
      - curl https://sh.rustup.rs -sSf > install.sh
      - sh install.sh -y
      - . $HOME/.cargo/env
  pre_build:
    commands:
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
  build:
    commands:
      - cargo build --release
      - docker build ./ -t $TARGET_IMAGE_NAME:$CODEBUILD_SOURCE_VERSION
  post_build:
    commands:
      - docker push $TARGET_IMAGE_NAME:$CODEBUILD_SOURCE_VERSION