[package]
name = "beatoraja_play_recommend_server"
version = "0.1.0"
authors = ["katand <katandps@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "0.2", features = ["macros"] }
warp = "0.2"

mobc-postgres = { version = "0.5", features = ["with-chrono-0_4"] }
mobc = "0.5"

env_logger = "0.7.1"
serde = { version = "1.0", features = ["derive"] }
serde_derive = "1.0"
serde_json = "1.0"
thiserror = "1.0"
chrono = { version = "0.4", features = ["serde"]}


#beatoraja_play_recommend = { git = "https://github.com/katandps/beatoraja_play_recommend.git"}
#開発用
beatoraja_play_recommend = { path = "../beatoraja_play_recommend" }