[package]
name = "beatoraja_play_recommend_server"
version = "0.1.0"
authors = ["katand <katandps@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = [
    "./mysql"
]

[dependencies]
actix-web = "3.0.0-alpha.1"
env_logger = "0.7.1"
serde = "1.0.110"
#serde = {version = "1.0.106", feature = ["derive"]}
actix-rt = "1.1.1"

mysql = {path = "mysql"}

#beatoraja_play_recommend = { git = "https://github.com/katandps/beatoraja_play_recommend.git"}
#開発用
beatoraja_play_recommend = {path = "../beatoraja_play_recommend"}