version: '3'

services:
  app:
    image: 847110695266.dkr.ecr.ap-northeast-1.amazonaws.com/beatoraja_recommend_server:latest
    container_name: app
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./files:/app/files
      - ./config.toml:/app/config.toml
