version: '2'
#ローカル開発用Docker-compose設定

services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    volumes:
      - ./target/debug/beatoraja_play_recommend_server:/app/beatoraja_play_recommend_server
      - ./config.toml:/app/config.toml
      - ./.env:/app/.env
      - ./files:/app/files
    entrypoint:
      - /app/beatoraja_play_recommend_server
    ports:
      - "80:80"
    depends_on:
      - db
  db:
    container_name: db
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_PORT: 3306
    ports:
      - "3306:3306"
    volumes:
      - ./db/mysql_data:/var/lib/mysql
  console:
    container_name: console
    build:
      context: .
      dockerfile: docker/console/Dockerfile
    volumes:
      - ./:/app/
    working_dir: /app
    depends_on:
      - db
      - app