version: '2'
#ローカル開発用Docker-compose設定

services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: dev/Dockerfile
    volumes:
      - ./target/debug/beatoraja_play_recommend_server:/app/beatoraja_play_recommend_server
      - ./config.toml:/app/config.toml
      - ./files:/app/files
    entrypoint:
      - /app/beatoraja_play_recommend_server
    ports:
      - "80:80"
    depends_on:
      - db
  db:
    container_name: db
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_PORT: 3306
    ports:
      - "3306:3306"