version: '2'
#ローカル開発用Docker-compose設定

services:
  app:
    build: .
    image: ubuntu
    volumes:
      - ./target/debug/beatoraja_play_recommend_server:/app/beatoraja_play_recommend_server
    entrypoint:
      - /app/beatoraja_play_recommend_server
    ports:
      - "80:80"
    depends_on:
      - db
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_PORT: 3306
    ports:
      - "3306:3306"